# Fun Mooc : PYTHON3 : Des fondamentaux aux concepts avancés du langage
## Semaine 2: Notions de base pour écrire son premier programme en Python

### Codage jeux de caractere et Unicode

#### Flux de bits

- Le décodage : definir une convention je découpe le flux de bits en blocs d'une certaine taille

Le codage en bloc de 7 bits : décodage ascii = 128 caractères

Un jeu de caracteres est une table de codes pour chaque caractere ici ascii

Avec seulement 128 carcatères en ASCII il a donc fallu utiliser des codages étendus : ascii étendus sur 8 bits

- Le Codage Unicode : coder l'integralité des carcateres du monde soit+ de120 000 caracteres codés.

Unicode définit la liste des caracteres et utilise les encodages utf-8 utf-16 et utf-32

On peut appeler les méthodes encode et decode
Il faudrait specifier explicitement UTF-8
De préférence écrire le code en anglais et mefiance avec accents et cédilles

- on peut mettre des accents dans les noms de variable
- on peut mettre des accents dans des chaines de caractère
- on peut mettre des accents dans les commentaires (#)

### Les Chaînes de caractères

Les chaînes de caractères sont des objets immuables : une fois crées elles ne peuvent être modifiées.

Les méthodes associées aux chaînes de caractère et qui permettent de les manipuler créent un nouvel objet chaîne de caractère.

Les chaînes de carctère sont de type str

In [14]:
'spam'

'spam'

In [15]:
"spam" # crée une autre chaine de carctère, équivalente à la première

'spam'

In [16]:
s='spam'

In [19]:
str? #permet d'obtenir de l'aide sur les chaînes de caractère

SyntaxError: invalid syntax (<ipython-input-19-e4f9d81b6c62>, line 1)

In [3]:
dir(str) 
# donne la liste exhaustive de toutes les méthodes associées 
# aux chaînes de caractère

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [4]:
'un mooc sur python'.title() # met des majuscules à chaque mot

'Un Mooc Sur Python'

In [5]:
s="Le poulet c'est bon" 
# interet d'avoir ladouble notation possible guillemets ou apostrophes : 
# s'il y a une apostrophe dans la chaîne (c'est)
# on a donc tout interet à utiliser les guillemets
s.replace('poulet','spam') 
# attention : on crée un nouvel objet donc la variable s n'est pas modifiée

"Le spam c'est bon"

In [6]:
s # on vérifie que s n'est pas modifiée

"Le poulet c'est bon"

In [7]:
'123'

'123'

In [8]:
'123'.isdecimal() 
# permet de savoir si la chaine de caractère 
# représente bien un nombre décimal

True

In [9]:
# Comment formater une chaîne de caractère
n='lulu'
age=38
"{} {}".format(n,age) #substitue respectivement n et age à la première et à la deuxième accolade

'lulu 38'

In [10]:
"{} a {} ans".format(n,age)

'lulu a 38 ans'

In [11]:
f"{n} a {age} ans" # crée un f-string plus expressive

'lulu a 38 ans'

### Unicode

In [12]:
"noël, été"

'noël, été'

In [13]:
"\u03a6"

'Φ'

Sous Python on peut passer facilement des type bytes aux chaînes de caractère et inversement.

Les types bytes sont utilisés pour encoder les flux de bits.



In [14]:
s='un noël en été'
print(s)

un noël en été


In [15]:
en=s.encode('utf8')
print(en)

b'un no\xc3\xabl en \xc3\xa9t\xc3\xa9'


Le type bytes contient des octets donc codés sur 8 bits

In [16]:
en.decode('utf8')

'un noël en été'

Il y a des problèmes parce que les auteurs des codes sources ne spécifient pas  le type d'encodage utilisé. D'où la recommandation qui est faite de toujours utiliser utf8

In [17]:
#decoupage et assemblage de chaînes de caractère : split et join
'abc=:=def=:=ghi=:=jkl'.split('=:=') #split permet de découper

['abc', 'def', 'ghi', 'jkl']

In [19]:
"=:=".join(['abc','def', 'ghi','jkl']) # et join d'associer

'abc=:=def=:=ghi=:=jkl'

In [20]:
"abcdefabcdefabcdef".replace("abc","zoo")

'zoodefzoodefzoodef'

In [21]:
# Nettoyage avec strip
" abc:def:ghi".replace(" ","")

'abc:def:ghi'

In [23]:
" \tune chaîne avec des trucs qui dépassent \n".strip()

'une chaîne avec des trucs qui dépassent'

In [24]:
'abc;def;ghi;jkl;'.strip(';').split(';')

['abc', 'def', 'ghi', 'jkl']

In [26]:
# donne l'indice de la première occurence où se trouve une sous-chaîne
"abcdefcdefghefghijk".find("def")

3

In [27]:
# ou -1 si la chîne n'est pas présente
"abcdefcdefghefghijk".find("zoo")

-1

In [28]:
# rfind fonctionne comme find mais en partant de la fin
"abcdefcdefghefghijk".rfind("fgh")

13

In [29]:
# mais effectivement le résultat est toujours calculé par rapport 
# au début de la chaîne. Les indices commençent à 0
# la notation ma_chaine[n] permet d'accéder 
# au n+1 ème carctère de la chaîne.
"abcdefcdefghefghijk"[13]

'f'

In [30]:
# chercher si une sous chaîne est dans une autre chaîne : c'est in !
"def" in "abcdefcdefghefghijk"

True

In [31]:
# count permet de compter le nombre d'occurences d'une sous chaîne
"abcdefcdefghefghijk".count("ef")

3

In [33]:
"monty PYTHON".title()

'Monty Python'

In [34]:
"monty PYTHON".upper()

'MONTY PYTHON'

In [35]:
"monty PYTHON".lower()

'monty python'

In [36]:
"monty PYTHON".swapcase()

'MONTY python'

In [37]:
"monty PYTHON".capitalize()

'Monty python'

### Les f-string

In [38]:
# des variables
prenom,nom,age ='Jean','Dupont',35

In [42]:
# mon prmier f-string
f"{prenom} {nom} a {age} ans"

'Jean Dupont a 35 ans'

In [43]:
# toutes expressions autorisées dans les {}
f"dans 10 ans {prenom} aura {age+10} ans"

'dans 10 ans Jean aura 45 ans'

In [44]:
# on peut aussi mettre des appels à fonction
notes =[12,15,19]
f"nous avons pour l'instant {len(notes)} notes"

"nous avons pour l'instant 3 notes"

### Precision des arrondis

In [48]:
from math import pi
# un f-string
f"pi avec seulement deux chiffres après la virgule {pi:.2f}"

'pi avec seulement deux chiffres après la virgule 3.14'

In [53]:
from math import pi
# un f-string
f"pi avec seulement deux chiffres après la virgule {pi:.48f}"

'pi avec seulement deux chiffres après la virgule 3.141592653589793115997963468544185161590576171875'

In [54]:
# la methode input renvoie toujours une chaîne de carctère !!
# donc penser à vérifier/convertir , par exemple en un nombre entier 
# avec la méthode int
n=int(input("Nombre de lignes ?"))+3
print(n)

Nombre de lignes ?10
13


In [55]:
'""'

'""'

In [57]:
"'"

"'"

In [58]:
'"'"

SyntaxError: EOL while scanning string literal (<ipython-input-58-197f6db2089c>, line 1)

In [59]:
'spam"'

'spam"'

### Les Séquences

Ce sont des ensembles finis et ordonnés d'éléments indicés de 0 à n-1 si on a n éléments

Notamment : listes, tuples, chaînes de caractère et les bytes...

In [75]:
s = 'egg, bacon'

In [76]:
s[0]

'e'

In [79]:
s[9]

'n'

In [80]:
len(s)

10

In [81]:
'egg'in s

True

In [82]:
'egg' not in s

False

In [85]:
s+' and beans' 
# crée bien une nouvelle chaîne de caractère var elles ne sont pas mutables

'egg, bacon and beans'

In [86]:
s.index('g')

1

In [87]:
s.count('g')

2

In [88]:
min(s)

' '

In [91]:
max(s) # comme ce sont des chaines de caractère on utilise ici l'ordre lexicographique

'o'

In [92]:
'x'*30

'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

In [94]:
# Le Slicing d'une séquence
s[0:3] # retourne les éléments de 0 jusqu' 2 (3-1)

'egg'

In [97]:
s[:3] # du début jusqu'à 2 inclus

'egg'

In [98]:
s[5:] # de 5 inclus judqu'à la fin

'bacon'

In [99]:
s[:] # retourne une copie de la chaîne de caractère
# c'est une opération de chalocopie !

'egg, bacon'

In [101]:
s[0:10:2] # parcourir les élément de 0 à 10 (exclus) pa pas de 2 !

'eg ao'

In [102]:
s[::2] # parcourt du début à la fin par pas de 2

'eg ao'

In [104]:
s[:8:3] # parcourt à partir du début jusquà 8 exclus (donc 7) 
# par pas de 3

'e,a'

In [105]:
s[2::3] # parcout la liste de 2 jusqu'àla fin avec un pas de 3

'gbo'

In [107]:
s[5:100]

'bacon'

In [108]:
s[100:200]

''

In [109]:
s[-10:-7]

'egg'

In [110]:
s[:-3]

'egg, ba'

In [111]:
s[::-1]

'nocab ,gge'

In [112]:
s[2:0:-1]

'gg'

In [113]:
chaine='abcdefghijklmnopqrstuvwxyz'
print(chaine)

abcdefghijklmnopqrstuvwxyz


In [114]:
chaine [2:6] # affiche à partir de 2 jusqu'à 5 inclus : 'cdef'

'cdef'

In [115]:
chaine[0:3]+chaine[3:7]==chaine[0:7]

True

In [116]:
chaine[:6] # borne ommise à gauche on part du début

'abcdef'

In [117]:
chaine[24:] # borne ommise à droite on va jusqu'à la fin

'yz'

In [119]:
chaine[:] # crée une copie 

'abcdefghijklmnopqrstuvwxyz'

In [121]:
chaine [3:-3] # de d à x (exclus) donc w

'defghijklmnopqrstuvw'

In [124]:
chaine [-3:] # de -3 c'est à dire x jusqu'à la fin

'xyz'

In [125]:
chaine[3:-3:2] #pas de 2

'dfhjlnprtv'

In [126]:
chaine[3:-4:2]

'dfhjlnprtv'

In [127]:
chaine[-3:3]

''

In [128]:
chaine[-3:3:-2]

'xvtrpnljhf'

In [129]:
liste=[0,2,4,8,16,32,64,128]

In [131]:
liste [-1:1:-2] #de 128 jusquà 2 exclus (donc 4) de 2 en deux : 128, 32, 8

[128, 32, 8]

In [132]:
liste[2:4]

[4, 8]

In [139]:
import numpy as np
un_cinq = np.array([1,2,3,4,5])
un_cinq

array([1, 2, 3, 4, 5])

In [138]:
array=10*un_cinq[:,np.newaxis]+un_cinq
array

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45],
       [51, 52, 53, 54, 55]])

In [140]:
centre=array[1:4,1:4]
centre

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [141]:
coins=array[::4,::4]
coins

array([[11, 15],
       [51, 55]])

In [142]:
tete_en_bas=array[::-1,:]
tete_en_bas

array([[51, 52, 53, 54, 55],
       [41, 42, 43, 44, 45],
       [31, 32, 33, 34, 35],
       [21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15]])

In [143]:
chaine='douarnenez'

In [145]:
chaine.index('z')==len(chaine)-1

True

In [148]:
chaine[-3:]=='nez'

True

In [147]:
chaine[1:3]+chaine[3:5]+chaine[5:]==chaine[1:]

True

### Les Listes

la taille de l'objet liste est indépendante des objets référencés.

La liste est mutable là où il est stocké, pas besoin de faire une copie de l'objet pour le modifier.

C'est une séquence donc toutes le méthodes vues pour les séquences sont disponibles.

In [205]:
a=[] # crée une liste vide

In [206]:
type(a)

list

In [207]:
i=4
a=[i,'spam',3.2, True] 
# la liste ne stocke pas ces objets
# elle ne stocke que des références à ces objets
a

[4, 'spam', 3.2, True]

In [208]:
a[0]

4

In [209]:
a[0]=6
a

[6, 'spam', 3.2, True]

In [210]:
a[0]+=10
a

[16, 'spam', 3.2, True]

In [211]:
a[1:3]

['spam', 3.2]

In [212]:
a[1:3]=[1,2,3] 
# affectation sur slice
# deux opérations indépendantes : 
# enlève tous les éléments de 1 à 2 (3 exclus), ici 'spam' et 3.2
# insère les éléments [1,2,3] à la place
a

[16, 1, 2, 3, True]

In [213]:
a[1:3]=[]
a

[16, 3, True]

In [214]:
del a[1:2]
a

[16, True]

In [215]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [216]:
# methode append
list.append?

In [217]:
a.append('18')
a

[16, True, '18']

In [218]:
a.extend([1,2,3])
a

[16, True, '18', 1, 2, 3]

In [220]:
a=[1,5,3,1,7,9,2]
a.sort()
a

[1, 1, 2, 3, 5, 7, 9]

In [221]:
s='spam egg beans'
a=s.split()
a

['spam', 'egg', 'beans']

In [223]:
a[0]=a[0].upper()
a

['SPAM', 'egg', 'beans']

In [224]:
" ".join(a)

'SPAM egg beans'

In [255]:
# Applications Compléments
liste=[0,1,2,3]
liste.append('app')
print('liste',liste)

liste [0, 1, 2, 3, 'app']


In [256]:
liste2=['ex1','ex2']
liste.extend(liste2)
print('liste',liste)

liste [0, 1, 2, 3, 'app', 'ex1', 'ex2']


In [257]:
a1=list(range(3))
print(a1)

[0, 1, 2]


In [258]:
a2=list(range(10,13))
a3=a1+a2
print('a1',a1)
print('a2',a2)
print('a3',a3)

a1 [0, 1, 2]
a2 [10, 11, 12]
a3 [0, 1, 2, 10, 11, 12]


In [259]:
# l'adddition de liste est une concaténation, elle crée un objet nouveau
# les objets ajoutés ne sont pas modifiés.

In [260]:
liste.insert(2,'1 bis')
print ('liste',liste)

liste [0, 1, '1 bis', 2, 3, 'app', 'ex1', 'ex2']


In [261]:
liste

[0, 1, '1 bis', 2, 3, 'app', 'ex1', 'ex2']

In [262]:
liste[5:5]=['3bis']
liste

[0, 1, '1 bis', 2, 3, '3bis', 'app', 'ex1', 'ex2']

In [263]:
liste.remove(3)
liste

[0, 1, '1 bis', 2, '3bis', 'app', 'ex1', 'ex2']

In [264]:
popped=liste.pop(0)
popped

0

In [265]:
liste

[1, '1 bis', 2, '3bis', 'app', 'ex1', 'ex2']

In [266]:
popped=liste.pop()
popped

'ex2'

In [267]:
liste

[1, '1 bis', 2, '3bis', 'app', 'ex1']

In [268]:
liste.reverse()
liste

['ex1', 'app', '3bis', 2, '1 bis', 1]

In [269]:
liste2=liste[::-1]
liste2

[1, '1 bis', 2, '3bis', 'app', 'ex1']

In [270]:
liste # liste2 est une copie l'objet initial liste n'est pas modifié

['ex1', 'app', '3bis', 2, '1 bis', 1]

### Tri de Listes

In [271]:
liste=[8,7,4,3,2,9,1,5,6]
print('avant tri',liste)
liste.sort()
print('après tri',liste)

avant tri [8, 7, 4, 3, 2, 9, 1, 5, 6]
après tri [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [272]:
liste1=[3,2,9,1]
liste2=sorted(liste1)
liste2

[1, 2, 3, 9]

In [274]:
liste.sort(reverse=True)
liste

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [276]:
# ça ne fonctionne pas sur les complexes 
# parce qu'il n'y a pas de relation d'oredre dans C !
liste=['spam','egg','bacon','beef']
liste.sort()
liste
# C'est un tri lexicographique

['bacon', 'beef', 'egg', 'spam']

In [280]:
'a'<'z'

True

In [281]:
'Z'<'a'

True

In [282]:
'z'<'A'

False

In [283]:
liste=['abc','Zoo']
liste.sort()
liste

['Zoo', 'abc']

In [329]:
liste=[0,1,2,3]

In [330]:
liste.insert(2,4)
liste

[0, 1, 4, 2, 3]

In [331]:
liste.remove(4)
liste

[0, 1, 2, 3]

In [332]:
liste[2:3]=[4]
liste

[0, 1, 4, 3]

In [333]:
liste.remove(4)
liste

[0, 1, 3]

In [334]:
liste.insert(2,2)
liste

[0, 1, 2, 3]

In [335]:
liste[2:2]=[4]
liste

[0, 1, 4, 2, 3]

In [338]:
liste.remove(4)
liste

[0, 1, 2, 3]

In [339]:
suivant=liste.pop(0)
print(suivant, liste)

0 [1, 2, 3]


In [340]:
liste.insert(0,0)
liste

[0, 1, 2, 3]

In [341]:
del liste[0]
liste

[1, 2, 3]

In [342]:
liste.insert(0,0)
liste

[0, 1, 2, 3]

In [343]:
suivant=liste[0];del liste[0]
print(suivant,liste)

0 [1, 2, 3]


In [344]:
liste.insert(0,0)
liste

[0, 1, 2, 3]

In [345]:
liste.sort(reverse=True)
liste

[3, 2, 1, 0]

In [346]:
liste.sort()

In [347]:
liste

[0, 1, 2, 3]

In [348]:
liste.sort();liste.reverse()
liste

[3, 2, 1, 0]

In [350]:
liste.sort()
liste

[0, 1, 2, 3]

In [351]:
liste.reverse()
liste

[3, 2, 1, 0]

In [352]:
liste.reverse()
liste

[0, 1, 2, 3]

In [353]:
sorted(liste,reverse=True)
liste

[0, 1, 2, 3]

In [355]:
if 1<2 :
    print('oui')
else:
    print('non')

oui


### Les boucles For et les Fonctions

La Factorisation du Code : boucles For et les Fonctions.

L'indentation représente 4 caractères vers la droite.

Définir une fonction = Implémenter une fonction.

L'objet None est un singleton prédéfini par Python.

In [2]:
L=[i**2 for i in range(10)]
L

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [3]:
str(1)

'1'

In [4]:
a = []
for n in [1, 2, '3', 4, 'FIN']:
    a.append(str(n))
print(",".join(a))

1,2,3,4,FIN


In [5]:
def to_str(a):
    tmp = []
    for i in a:
        tmp.append(str(i))
    return " ".join(tmp)   

In [6]:
to_str('123')

'1 2 3'

In [7]:
to_str([1,2,3])

'1 2 3'

In [8]:
to_str(['1','2','3'])

'1 2 3'

In [11]:
to_str(['123'])

'123'

In [12]:
def label(prenom, note):
    "votre code"
    if 0<=note<=9:
        return f"{prenom} est recalé"
    if 10<=note<=15:
        return f"{prenom} est reçu"
    else :
        return f"Félicitations à {prenom}"

In [13]:
label('John',7)

'John est recalé'

In [14]:
label('Michel',20)

'Félicitations à Michel'

In [15]:
import string
chaine=string.ascii_lowercase
print(chaine)

abcdefghijklmnopqrstuvwxyz


In [16]:
chaine[ -3::-3 ] == "xurolifc"

True

In [17]:
def inconnue(composite, connue):
    "votre code"
    a = composite.split(connue)
    a.pop()
    a.pop(0)
    b=a[0]
    return b

In [19]:
inconnue(
  '64a508d464a',
  '64a')

'508d4'

In [20]:
inconnue(
  '7a546805d1a97a54',
  '7a54')

'6805d1a9'

In [21]:
inconnue(
  'd8e79c1238d8e79',
  'd8e79')

'c1238'

In [22]:
inconnue(
  '3b24d8e54af3b24',
  '3b24')

'd8e54af'

In [47]:
def laccess(liste):
    if liste==[]:
        return
    elif len(liste)%2==0:
        return liste[len(liste)-1]
    else:
        p = len(liste)//2
        return liste[p]

In [48]:
laccess([])

In [49]:
laccess([1])

1

In [50]:
laccess(['spam', 2])

2

In [51]:
laccess(['spam', 2, 'bacon'])

2

In [52]:
laccess([1, 2, 3, 4])

4

In [53]:
laccess([1, 2, 3, 4, 5])

3

In [54]:
laccess('a')

'a'

In [55]:
laccess('ab')

'b'

In [56]:
laccess('abc')

'b'

In [57]:
laccess('abcd')

'd'

In [58]:
laccess('abcde')

'c'

In [59]:
laccess('')

IndexError: string index out of range